import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { fileURLToPath } from 'node:url';
const server=fileURLToPath(new URL('../server.mjs',import.meta.url));
const wait=ms=>new Promise(r=>setTimeout(r,ms));

test('AI 없이 직접 추가, 검증, 개별 간격, 업데이트와 이전 데이터 보존',async()=>{
  const dir=await mkdtemp(path.join(tmpdir(),'momo-no-ai-test-'));
  const bin=path.join(dir,'bin'),data=path.join(dir,'data');await mkdir(bin);await mkdir(data);
  await writeFile(path.join(dir,'package.json'),JSON.stringify({type:'module'}));
  await writeFile(path.join(data,'state.json'),JSON.stringify({watches:[{id:'legacy',name:'체험',demo:true}],notifications:[],schedule:24,provider:'claude'}));
  await writeFile(path.join(dir,'fetch.mjs'),`import fs from 'node:fs';const root=process.env.MOMO_FIXTURE;globalThis.fetch=async url=>{fs.appendFileSync(root+'/fetch-calls',url+'\\n');if(fs.existsSync(root+'/offline'))throw new TypeError('fetch failed');return new Response(JSON.stringify({version:'0.2.0',tag_name:'v0.2.0',versions:{stable:'0.2.0'},revision:1}),{status:url.includes('does-not-exist')?404:200});};`);
  await mkdir(path.join(dir,'global','alpha-tool'),{recursive:true});
  await writeFile(path.join(dir,'global','alpha-tool','package.json'),JSON.stringify({name:'alpha-tool',version:'0.1.0'}));
  const cli=`#!${process.execPath}
import fs from 'node:fs';import path from 'node:path';
const tool=path.basename(process.argv[1]),args=process.argv.slice(2),root=process.env.MOMO_FIXTURE;
const file=name=>path.join(root,tool+'-'+name);
const read=(name,fallback)=>{try{return fs.readFileSync(file(name),'utf8')}catch{return fallback}};
fs.appendFileSync(path.join(root,'calls'),JSON.stringify({tool,args})+'\\n');
if(tool==='brew')console.log(JSON.stringify({formulae:[{name:'zebra',tap:'homebrew/core',installed:[{version:'0.1.0',installed_on_request:true}]},{name:'dependency',tap:'homebrew/core',installed:[{version:'0.1.0',installed_on_request:false}]}],casks:[]}));
else if(tool==='npm')console.log(path.join(root,'global'));
else if(args[0]==='--version')console.log(tool+' '+read('version','0.1.0'));
else if(args[0]==='update'||args[0]==='upgrade'){
 if(args.includes('--help'))console.log('Update this CLI');else setTimeout(()=>{if(read('update-mode','success')==='fail')process.exitCode=1;else fs.writeFileSync(file('version'),'0.2.0');},350);
}else{process.exitCode=1;}
`;
  for(const name of ['claude','codex','gemini','opencode','bun','brew','npm'])await writeFile(path.join(bin,name),cli,{mode:0o755});
  await symlink(process.execPath,path.join(bin,'node'));
  const port=14329,origin=`http://127.0.0.1:${port}`;let child;
  const launch=async()=>{child=spawn(process.execPath,[server],{env:{...process.env,PATH:bin,MOMO_PORT:String(port),MOMO_DATA_DIR:data,MOMO_FIXTURE:dir,NODE_OPTIONS:`--import=${path.join(dir,'fetch.mjs')}`},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('startup timeout')),10000);child.stdout.once('data',()=>{clearTimeout(timer);resolve();});child.once('exit',()=>{clearTimeout(timer);reject(new Error('early exit'));});});};
  const request=async(endpoint,body)=>{const r=await fetch(origin+'/api/'+endpoint,body?{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)}:{});return{status:r.status,data:await r.json()};};
  const state=async()=>(await request('state')).data;
  const until=async(predicate)=>{for(let i=0;i<80;i++){const s=await state();if(predicate(s))return s;await wait(100);}throw new Error('state timeout');};
  try{
    await launch();let s=await state();assert.equal(s.onboarded,false);assert.equal(s.watches.length,0);assert.equal(s.presets.length,4);assert.deepEqual(s.presets.map(p=>p.id),['claude','codex','gemini','grok']);assert.ok(!('provider' in s));assert.ok(!('connection' in s));
    for(const endpoint of ['chat','connect','login','login/cancel','providers/refresh'])assert.equal((await request(endpoint,{provider:'claude',message:'안녕'})).status,404);
    await request('onboarding',{presetIds:['claude','codex']});s=await until(s=>!s.checking&&s.watches.every(w=>w.status==='ok'));assert.deepEqual(s.watches.map(w=>w.hours),[6,6]);
    const claude=s.watches.find(w=>w.name==='Claude Code'),codex=s.watches.find(w=>w.name==='Codex');
    const preview=await request('preview',{input:'typescript'});assert.equal(preview.status,200);assert.equal(preview.data.version,'0.2.0');assert.equal((await state()).watches.length,2);
    const targets=['','https://example.com/owner/repo','http://github.com/owner/repo','https://github.com/a/b?token=x','https://user:secret@github.com/a/b','a/b','$(touch /tmp/unsafe)','https://github.com/owner'];
    for(const input of targets)assert.equal((await request('preview',{input})).status,400,input);
    assert.equal((await request('preview',{input:'does-not-exist'})).status,502);assert.equal((await state()).watches.length,2);
    assert.equal((await request('preview',{input:'@scope/package'})).status,200);
    const gh=await request('preview',{input:'https://github.com/Example/Repo.git/'});assert.equal(gh.data.target,'example/repo');assert.equal(gh.data.source,'github');
    await writeFile(path.join(dir,'offline'),'yes');assert.equal((await request('manage',{action:'add',input:'typescript',hours:12})).status,502);assert.equal((await state()).watches.length,2);await rm(path.join(dir,'offline'));
    const replies=await Promise.all([request('manage',{action:'add',input:'typescript',hours:12}),request('manage',{action:'add',input:'typescript',hours:12})]);assert.deepEqual(replies.map(r=>r.status).sort(),[200,409]);
    s=await until(s=>!s.checking);const added=s.watches.find(w=>w.target==='typescript');assert.equal(added.hours,12);assert.equal(added.canUpdate,false);assert.equal(s.watches.length,3);
    assert.equal((await request('preview',{input:'typescript'})).status,409);
    assert.equal((await request('manage',{action:'add',input:'left-pad',hours:2})).status,400);
    await request('manage',{action:'add',input:'https://github.com/Example/Repo',hours:24});assert.equal((await request('preview',{input:'https://github.com/example/repo'})).status,409);
    await request('manage',{action:'schedule',id:codex.id,hours:3});s=await state();assert.equal(s.watches.find(w=>w.id===codex.id).hours,3);assert.equal(s.watches.find(w=>w.id===claude.id).hours,6);
    assert.equal((await request('manage',{action:'schedule',hours:3})).status,404);
    await request('manage',{action:'remove',id:added.id});assert.ok(!(await state()).watches.some(w=>w.id===added.id));
    s=await until(s=>!s.checking);const notice=s.notifications.find(n=>n.watchId===codex.id);await request('manage',{action:'dismiss',id:notice.id});assert.ok((await state()).watches.find(w=>w.id===codex.id).update);
    await writeFile(path.join(dir,'codex-update-mode'),'fail');assert.equal((await request('manage',{action:'update',id:codex.id})).status,200);s=await until(s=>!s.updatingId);assert.equal(s.watches.find(w=>w.id===codex.id).status,'error');assert.ok(s.watches.find(w=>w.id===codex.id).update);
    await writeFile(path.join(dir,'codex-update-mode'),'success');await request('manage',{action:'update',id:codex.id});assert.equal((await request('manage',{action:'remove',id:codex.id})).status,409);s=await until(s=>!s.updatingId);assert.equal(s.watches.find(w=>w.id===codex.id).installedVersion,'0.2.0');assert.equal(s.watches.find(w=>w.id===codex.id).update,null);
    const stopped=once(child,'exit');child.kill('SIGTERM');await stopped;await launch();s=await state();assert.equal(s.onboarded,true);assert.equal(s.watches.find(w=>w.id===codex.id).hours,3);
    const preparedCount=(await state()).watches.length;
    const prepared=await request('presets/preview-batch',{ids:['gemini','grok']});
    assert.equal(prepared.status,200);assert.equal(prepared.data.items[0].installedVersion,'0.1.0');assert.equal(prepared.data.items[1].installedVersion,null);
    assert.equal((await state()).watches.length,preparedCount);
    assert.equal((await request('presets/preview-batch',{ids:['bun']})).status,400);
    assert.equal((await request('presets/preview-batch',{ids:['gemini','gemini']})).status,400);
    assert.equal((await request('manage',{action:'add-presets',items:[{presetId:'gemini',hours:2}]})).status,400);
    await writeFile(path.join(dir,'offline'),'yes');
    assert.equal((await request('manage',{action:'add-presets',items:[{presetId:'gemini',hours:3},{presetId:'grok',hours:12}]})).status,502);
    assert.equal((await state()).watches.length,preparedCount);await rm(path.join(dir,'offline'));
    assert.equal((await request('manage',{action:'add-presets',items:[{presetId:'gemini',hours:3},{presetId:'grok',hours:12}]})).status,200);
    s=await until(s=>!s.checking&&s.watches.filter(w=>['@google/gemini-cli','@xai-official/grok'].includes(w.target)).every(w=>w.status==='ok'));
    const gemini=s.watches.find(w=>w.target==='@google/gemini-cli'),grok=s.watches.find(w=>w.target==='@xai-official/grok');
    assert.equal(gemini.hours,3);assert.equal(grok.hours,12);assert.ok(gemini.update);assert.equal(grok.update,undefined);assert.equal(gemini.canUpdate,false);assert.equal(grok.canUpdate,false);
    assert.equal((await request('manage',{action:'update',id:gemini.id})).status,409);
    assert.equal((await request('manage',{action:'add-presets',items:[{presetId:'gemini',hours:6}]})).status,409);
    for(const w of [gemini,grok])await request('manage',{action:'remove',id:w.id});
    const catalog=await request('installed');assert.equal(catalog.status,200);assert.deepEqual(catalog.data.items.map(i=>i.name),['alpha-tool','zebra']);assert.equal(catalog.data.warnings.length,0);
    const beforeCount=(await state()).watches.length;
    const batch=[{installedId:'homebrew:formula/zebra',hours:12},{installedId:'npm:alpha-tool',hours:3}];
    const review=await request('installed/preview-batch',{ids:batch.map(i=>i.installedId)});assert.equal(review.status,200);assert.equal(review.data.items.length,2);assert.equal((await state()).watches.length,beforeCount);
    assert.equal((await request('manage',{action:'add-many',items:[batch[0],{...batch[1],hours:2}]})).status,400);assert.equal((await state()).watches.length,beforeCount);
    assert.equal((await request('manage',{action:'add-many',items:[batch[0],{installedId:'npm:missing',hours:6}]})).status,404);assert.equal((await state()).watches.length,beforeCount);
    assert.equal((await request('manage',{action:'add-many',items:[batch[0],batch[0]]})).status,400);
    await writeFile(path.join(dir,'offline'),'yes');assert.equal((await request('manage',{action:'add-many',items:batch})).status,502);assert.equal((await state()).watches.length,beforeCount);await rm(path.join(dir,'offline'));
    const parallelBatch=await Promise.all([request('manage',{action:'add-many',items:batch}),request('manage',{action:'add-many',items:batch})]);assert.deepEqual(parallelBatch.map(r=>r.status).sort(),[200,409]);
    s=await until(s=>!s.checking);assert.equal(s.watches.length,beforeCount+2);assert.equal(s.watches.find(w=>w.target==='formula/zebra').hours,12);assert.equal(s.watches.find(w=>w.target==='alpha-tool').hours,3);
    for(const watch of s.watches.filter(w=>['formula/zebra','alpha-tool'].includes(w.target)))await request('manage',{action:'remove',id:watch.id});
    const brewPreview=await request('installed/preview',{id:'homebrew:formula/zebra'});assert.equal(brewPreview.data.version,'0.2.0_1');assert.equal((await state()).watches.length,beforeCount);
    assert.equal((await request('installed/preview',{id:'homebrew:formula/../../secret'})).status,404);
    assert.equal((await request('manage',{action:'add',installedId:'homebrew:formula/zebra',hours:12})).status,200);
    s=await until(s=>!s.checking);const brew=s.watches.find(w=>w.source==='homebrew');assert.equal(brew.installedVersion,'0.1.0');assert.equal(brew.version,'0.2.0_1');assert.ok(brew.update);assert.equal(brew.canUpdate,true);assert.equal(brew.hours,12);
    assert.equal((await request('manage',{action:'add',installedId:'homebrew:formula/zebra',hours:12})).status,409);
    await request('manage',{action:'add',installedId:'npm:alpha-tool',hours:6});s=await until(s=>!s.checking);assert.equal(s.watches.find(w=>w.target==='alpha-tool').installedVersion,'0.1.0');
    const raw=JSON.parse(await readFile(path.join(data,'state.json'),'utf8'));assert.ok(raw.watches.some(w=>w.id==='legacy'));assert.equal(raw.provider,'claude');
    const calls=(await readFile(path.join(dir,'calls'),'utf8')).trim().split('\n').map(JSON.parse);assert.ok(calls.every(c=>['--version','update','upgrade'].includes(c.args[0])||(c.tool==='brew'&&c.args.join(' ')==='info --json=v2 --installed')||(c.tool==='npm'&&c.args.join(' ')==='root --global')));
    const denied=await fetch(origin+'/api/manage',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json'},body:'{"action":"check"}'});assert.equal(denied.status,403);
  }finally{if(child?.exitCode===null){const stopped=once(child,'exit');child.kill('SIGTERM');await stopped;}await rm(dir,{recursive:true,force:true});}
});
